language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm postinstall
deploy:
  provider: heroku
  api_key:
    secure: R35lajw7f4ZaCziSSRuLFrpghB4nZoUnZHhqjM3ZiyntFhfFsSR+8HMYWRexd5PSbjw6IiVHT6MI7F0e933/0SIh8EWB3yPlf4hXpvLcjvZL45oUqUJSkcSaCjS6G8XWvISSMrtj4vStkVt4KC2LUhJ0tos51qBXHqGLGCogiNB6vaHjES2wuvOqbK7MYaffDvfAnyldL7PDPOpo/vFJkXtxsbK+s+Gi4XSNtad1INwigvqp96owfykD5Or8jr42N7h6BAC4nNvFLHuqXvk6HCNgxTWtGpc+a+HYmThDFy9UtE5fJCn/g9ipoe2fINH5DpeOrNfDMcYk8enurPtBKQE3EVyqkRZ4Y0vI/0EYFM61fRo4PwpZBS62ekhJPhmTYRFG5GMux2pNzYSk7pLGUs4cwwXQvb2kX8dBS9K6g4rI3YYLeQoDFbXMXsMjOFdSiYNkzahAy1CNm0Qt/0GFU/7NJAabfzntzF0Ju+uf2O5HSQASWzfXYMrmSN6sw1rFMfXRY8pTckTE51pMnjAR9/CDe26lXcdHEJVg8Lm28IpP4btdDMg1BX7+cv2W+X1bD5bTr1V0Rw3ljjvqOofNfZCtMNOVH738hmuNK8FRkK3y4CMtb+9ZDjP1mX+AMaIadg9msSWalwfAuXIc9WRuTchRA9cEgM6Pn0VV8yxZBYo=
  app: jjpaulo2
  edge: true
  run:
  - npm install
  - npm postinstall
  - npm start
